/*Generated by xorm 2023-07-12 16:59:56, from dameng to dameng*/

CREATE SEQUENCE SEQ_TEST_DUMP_STRUCT 
	minvalue 1
	   nomaxvalue
	   start with 1
	   increment by 1
	   nocycle
	nocache;
CREATE TABLE "test_dump_struct" ("id" BIGINT NOT NULL, "name" VARCHAR2(255) NULL, "is_man" BIT NULL, "created" TIMESTAMP(6) NULL, CONSTRAINT PK_test_dump_struct PRIMARY KEY ("id"));
INSERT INTO "test_dump_struct" ("id", "name", "is_man", "created") VALUES (1,CONCAT('1'),1,CONCAT('2023-07-12 16:59:56'));
INSERT INTO "test_dump_struct" ("id", "name", "is_man", "created") VALUES (2,CONCAT('2', CHAR(10)),0,CONCAT('2023-07-12 16:59:56'));
INSERT INTO "test_dump_struct" ("id", "name", "is_man", "created") VALUES (3,CONCAT('3;'),0,CONCAT('2023-07-12 16:59:56'));
INSERT INTO "test_dump_struct" ("id", "name", "is_man", "created") VALUES (4,CONCAT('4', CHAR(10), ';', CHAR(10), ''''''),0,CONCAT('2023-07-12 16:59:56'));
INSERT INTO "test_dump_struct" ("id", "name", "is_man", "created") VALUES (5,CONCAT('5''', CHAR(10)),0,CONCAT('2023-07-12 16:59:56'));
