/*Generated by xorm 2023-07-26 16:06:45, from sqlite3 to mysql*/

SET sql_mode='NO_BACKSLASH_ESCAPES';
CREATE TABLE IF NOT EXISTS `test_dump_table_struct` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `data` BLOB NULL, `name` VARCHAR(255) NULL, `is_man` TINYINT(1) NULL, `created` DATETIME NULL);
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (1,NULL,'1',1,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (2,CONCAT(CHAR(0), CHAR(1), CHAR(2)),CONCAT('2', CHAR(10)),0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (3,'0x000102','3;',0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (4,'Help',CONCAT('4', CHAR(10), ';', CHAR(10), ''''''),0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (5,'0x48656c70',CONCAT('5''', CHAR(10)),0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (6,'48656c70',CONCAT('6\n''', CHAR(10)),0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (7,CONCAT('7\n''', CHAR(13), CHAR(10)),CONCAT('7\n''', CHAR(13), CHAR(10)),0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (8,NULL,'x0809ee',0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (9,NULL,'090a10',0,'2023-07-26T08:06:45Z');
