/*Generated by xorm 2023-07-26 16:06:45, from sqlite3 to postgres*/

CREATE TABLE IF NOT EXISTS "public"."test_dump_struct" ("id" SERIAL PRIMARY KEY  NOT NULL, "name" TEXT NULL, "is_man" INTEGER NULL, "created" TIMESTAMP NULL); ;
INSERT INTO "test_dump_struct" ("id", "name", "is_man", "created") VALUES (1,'1',1,'2023-07-26T08:06:45Z');
INSERT INTO "test_dump_struct" ("id", "name", "is_man", "created") VALUES (2,'2' || e'\x0a',0,'2023-07-26T08:06:45Z');
INSERT INTO "test_dump_struct" ("id", "name", "is_man", "created") VALUES (3,'3;',0,'2023-07-26T08:06:45Z');
INSERT INTO "test_dump_struct" ("id", "name", "is_man", "created") VALUES (4,'4' || e'\x0a' || ';' || e'\x0a' || '''''',0,'2023-07-26T08:06:45Z');
INSERT INTO "test_dump_struct" ("id", "name", "is_man", "created") VALUES (5,'5''' || e'\x0a',0,'2023-07-26T08:06:45Z');
SELECT setval('test_dump_struct_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "test_dump_struct"), 1), false);
