/*Generated by xorm 2023-07-26 16:06:45, from sqlite3 to mssql*/

IF NOT EXISTS (SELECT [name] FROM sys.tables WHERE [name] = '[test_dump_table_struct]' ) CREATE TABLE [test_dump_table_struct] ([id] BIGINT PRIMARY KEY IDENTITY NOT NULL, [data] VARBINARY(MAX) NULL, [name] VARCHAR(255) NULL, [is_man] BIT NULL, [created] DATETIME NULL);
SET IDENTITY_INSERT [test_dump_table_struct] ON;
INSERT INTO [test_dump_table_struct] ([id], [data], [name], [is_man], [created]) VALUES (1,NULL,N'1',1,N'2023-07-26T08:06:45Z');
INSERT INTO [test_dump_table_struct] ([id], [data], [name], [is_man], [created]) VALUES (2,CONVERT(VARBINARY(MAX), '0x000102', 1),N'2
',0,N'2023-07-26T08:06:45Z');
INSERT INTO [test_dump_table_struct] ([id], [data], [name], [is_man], [created]) VALUES (3,CONVERT(VARBINARY(MAX), '0x3078303030313032', 1),N'3;',0,N'2023-07-26T08:06:45Z');
INSERT INTO [test_dump_table_struct] ([id], [data], [name], [is_man], [created]) VALUES (4,CONVERT(VARBINARY(MAX), '0x48656c70', 1),N'4
;
''''',0,N'2023-07-26T08:06:45Z');
INSERT INTO [test_dump_table_struct] ([id], [data], [name], [is_man], [created]) VALUES (5,CONVERT(VARBINARY(MAX), '0x30783438363536633730', 1),N'5''
',0,N'2023-07-26T08:06:45Z');
INSERT INTO [test_dump_table_struct] ([id], [data], [name], [is_man], [created]) VALUES (6,CONVERT(VARBINARY(MAX), '0x3438363536633730', 1),N'6\n''
',0,N'2023-07-26T08:06:45Z');
INSERT INTO [test_dump_table_struct] ([id], [data], [name], [is_man], [created]) VALUES (7,CONVERT(VARBINARY(MAX), '0x375c6e270d0a', 1),N'7\n''
',0,N'2023-07-26T08:06:45Z');
INSERT INTO [test_dump_table_struct] ([id], [data], [name], [is_man], [created]) VALUES (8,NULL,N'x0809ee',0,N'2023-07-26T08:06:45Z');
INSERT INTO [test_dump_table_struct] ([id], [data], [name], [is_man], [created]) VALUES (9,NULL,N'090a10',0,N'2023-07-26T08:06:45Z');
