/*Generated by xorm 2023-07-12 16:59:56, from dameng to dameng*/

CREATE SEQUENCE SEQ_TEST_DUMP_TABLE_STRUCT2 
	minvalue 1
	   nomaxvalue
	   start with 1
	   increment by 1
	   nocycle
	nocache;
CREATE TABLE "test_dump_table_struct2" ("id" BIGINT NOT NULL, "created" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL, CONSTRAINT PK_test_dump_table_struct2 PRIMARY KEY ("id"));
