/*Generated by xorm 2023-07-26 16:06:45, from sqlite3 to sqlite3*/

CREATE TABLE IF NOT EXISTS `test_dump_struct` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `name` TEXT NULL, `is_man` INTEGER NULL, `created` DATETIME NULL);
INSERT INTO `test_dump_struct` (`id`, `name`, `is_man`, `created`) VALUES (1,'1',1,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_struct` (`id`, `name`, `is_man`, `created`) VALUES (2,'2' || X'0a',0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_struct` (`id`, `name`, `is_man`, `created`) VALUES (3,'3;',0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_struct` (`id`, `name`, `is_man`, `created`) VALUES (4,'4' || X'0a' || ';' || X'0a' || '''''',0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_struct` (`id`, `name`, `is_man`, `created`) VALUES (5,'5''' || X'0a',0,'2023-07-26T08:06:45Z');
