/*Generated by xorm 2023-07-26 16:06:45, from sqlite3 to postgres*/

CREATE TABLE IF NOT EXISTS "public"."test_dump_table_struct" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "data" BYTEA NULL, "name" VARCHAR(255) NULL, "is_man" BOOL NULL, "created" TIMESTAMP NULL); ;
INSERT INTO "test_dump_table_struct" ("id", "data", "name", "is_man", "created") VALUES (1,NULL,'1',true,'2023-07-26T08:06:45Z');
INSERT INTO "test_dump_table_struct" ("id", "data", "name", "is_man", "created") VALUES (2,'\x000102','2' || e'\x0a',false,'2023-07-26T08:06:45Z');
INSERT INTO "test_dump_table_struct" ("id", "data", "name", "is_man", "created") VALUES (3,'\x3078303030313032','3;',false,'2023-07-26T08:06:45Z');
INSERT INTO "test_dump_table_struct" ("id", "data", "name", "is_man", "created") VALUES (4,'\x48656c70','4' || e'\x0a' || ';' || e'\x0a' || '''''',false,'2023-07-26T08:06:45Z');
INSERT INTO "test_dump_table_struct" ("id", "data", "name", "is_man", "created") VALUES (5,'\x30783438363536633730','5''' || e'\x0a',false,'2023-07-26T08:06:45Z');
INSERT INTO "test_dump_table_struct" ("id", "data", "name", "is_man", "created") VALUES (6,'\x3438363536633730','6\n''' || e'\x0a',false,'2023-07-26T08:06:45Z');
INSERT INTO "test_dump_table_struct" ("id", "data", "name", "is_man", "created") VALUES (7,'\x375c6e270d0a','7\n''' || e'\x0d\x0a',false,'2023-07-26T08:06:45Z');
INSERT INTO "test_dump_table_struct" ("id", "data", "name", "is_man", "created") VALUES (8,NULL,'x0809ee',false,'2023-07-26T08:06:45Z');
INSERT INTO "test_dump_table_struct" ("id", "data", "name", "is_man", "created") VALUES (9,NULL,'090a10',false,'2023-07-26T08:06:45Z');
SELECT setval('test_dump_table_struct_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "test_dump_table_struct"), 1), false);
