/*Generated by xorm 2023-07-26 16:06:45, from sqlite3 to sqlite3*/

CREATE TABLE IF NOT EXISTS `test_dump_table_struct` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `data` BLOB NULL, `name` TEXT NULL, `is_man` INTEGER NULL, `created` DATETIME NULL);
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (1,NULL,'1',1,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (2,X'000102','2' || X'0a',0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (3,X'3078303030313032','3;',0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (4,X'48656c70','4' || X'0a' || ';' || X'0a' || '''''',0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (5,X'30783438363536633730','5''' || X'0a',0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (6,X'3438363536633730','6\n''' || X'0a',0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (7,X'375c6e270d0a','7\n''' || X'0d0a',0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (8,NULL,'x0809ee',0,'2023-07-26T08:06:45Z');
INSERT INTO `test_dump_table_struct` (`id`, `data`, `name`, `is_man`, `created`) VALUES (9,NULL,'090a10',0,'2023-07-26T08:06:45Z');
