name: test-mysql8
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  test-mysql8:
    concurrency:
      group: test-mysql8-${{ github.ref }}-${{ matrix.os }}-${{ matrix.go-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x, 1.19.x, 1.20.x]
        os: [ubuntu-latest]
    services:
      mysql8:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: xorm_test
        options: '-h localhost'
    env:
      OS: ${{ matrix.os }}
      TEST_MYSQL_HOST: 'localhost:3306'
      TEST_MYSQL_CHARSET: utf8mb4
      TEST_MYSQL_DBNAME: xorm_test
      TEST_MYSQL_USERNAME: root
      TEST_MYSQL_PASSWORD:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: test mysql8
        run: |
          make test-mysql && \
          TEST_CACHE_ENABLE=true make test-mysql
