name: test-tidb
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  test-tidb:
    concurrency:
      group: test-tidb-${{ github.ref }}-${{ matrix.os }}-${{ matrix.go-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x, 1.19.x, 1.20.x]
        os: [ubuntu-latest]
    services:
      tidb:
        image: pingcap/tidb:v3.0.3
        ports:
          - 4000:4000
        options: '-h localhost'
    env:
      OS: ${{ matrix.os }}
      TEST_TIDB_HOST: "localhost:4000"
      TEST_TIDB_DBNAME: xorm_test
      TEST_TIDB_USERNAME: root
      TEST_TIDB_PASSWORD:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: test tidb
        run: |
          make test-tidb
